package Server;

/**
* Server/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/java/workspace/0805/src/Server/Server.idl
* Sunday, August 6, 2017 5:16:50 o'clock PM EDT
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (Server.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.ServerInterfaceHelper.type ();
  }

}
