package Server;


/**
* Server/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/java/workspace/0805/src/Server/Server.idl
* Sunday, August 6, 2017 5:16:50 o'clock PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
